import sys
import os


def main():
    if "--generate-html" in sys.argv:
        generate_html()
    else:
        print("Hello from cicd-test!")


def generate_html():
    """Generate an HTML page and save it to the build directory."""
    os.makedirs("build", exist_ok=True)
    
    html_content = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CICD Test</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        }
        .container {
            text-align: center;
            background: white;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
        }
        h1 {
            color: #333;
            margin: 0;
        }
        p {
            color: #666;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Hello from CICD Test2! 🚀</h1>
        <p>This page was generated by Python and deployed via GitHub Actions.</p>
    </div>
</body>
</html>"""
    
    with open("build/index.html", "w") as f:
        f.write(html_content)
    
    print("HTML page generated successfully at build/index.html")


if __name__ == "__main__":
    main()